### ISSUE TITLE
 "java.lang.OutOfMemoryError: Java heap space" on Server

### ISSUE THREAD

**Issue by Lee-Yoonjoo** [yoonjoo3615/VertxEchoServerforUDPRequest#1]
My issue is that only Vertx Server throws "java.lang.OutOfMemoryError: Java heap space" in 15mins and it stops. You can also have a look the PerfMon Monitor Collector Graph on my post on Vertx Google group.
https://groups.google.com/forum/#!topic/vertx/ApUYfOzub24

**Comment by yoonjoo3615** [comment]
I upgraded vertx 3.2.2 to 3.5.0 
No more OOM on Server

**Comment by Lee-Yoonjoo** [comment]
I upgraded Vertx 3.2.2 to 3.5.0
No more OOM issue.
